<template>
    
</template>

<script>
    //盈利类因子
    const profitFactorInfo=[
      {
        name:"5日对数收益率",
        value:"logreturn_5",
        description:"5日对数收益率"
      },
      {
        name:"10日对数收益率",
        value:"logreturn_10",
        description:"10日对数收益率"
      },
      {
        name:"15日对数收益率",
        value:"logreturn_15",
        description:"15日对数收益率"
      },
      {
        name:"20日对数收益率",
        value:"logreturn_20",
        description:"20日对数收益率"
      },
      {
        name:"5日绝对收益率",
        value:"return_5",
        description:"5日绝对收益率"
      },
      {
        name:"10日绝对收益率",
        value:"return_10",
        description:"10日绝对收益率"
      },
      {
        name:"15日绝对收益率",
        value:"return_15",
        description:"15日绝对收益率"
      },
      {
        name:"20日绝对收益率",
        value:"return_20",
        description:"20日绝对收益率"
      },
    ]

    //价值类因子（估值、规模）
    const valueFactorInfo=[]

    //成长类因子
    const developFactorInfo=[]

    //情感类因子（交投）
    const emotionFactorInfo=[
      {
        name:"对数成交量变化率",
        value:"logvol",
        description:"5日对数成交量变化率"
      },
      {
        name:"10日对数成交量变化率",
        value:"logvol_10",
        description:"10日对数成交量变化率"
      },
      {
        name:"15日对数成交量变化率",
        value:"logvol_15",
        description:"15日对数成交量变化率"
      },
      {
        name:"20日对数成交量变化率",
        value:"logvol_20",
        description:"20日对数成交量变化率"
      },
      {
        name:"成交量变化率",
        value:"vol_change_rate",
        description:"单日成交量变化率"
      },
      {
        name:"5日成交量变化率",
        value:"vol_change_rate_5",
        description:"5日成交量变化率"
      },
      {
        name:"10日成交量变化率",
        value:"vol_change_rate_10",
        description:"10日成交量变化率"
      },
      {
        name:"20日成交量变化率",
        value:"vol_change_rate_20",
        description:"20日成交量变化率"
      },
      {
        name:"时间段成交量量比",
        value:"vol_relative_ratio_0",
        description:"5日成交量与历史成交量比"
      },
      {
        name:"AR（26日）",
        value:"ar",
        description:"人气指标（26日）"
      },
      {
        name:"AR(14日)",
        value:"ar_14",
        description:"人气指标（14日）"
      },
      {
        name:"BR（26日）",
        value:"br",
        description:"意愿指标（26日）"
      },
      {
        name:"BR（14日）",
        value:"br_14",
        description:"意愿指标（14日）"
      },
      {
        name:"OBV",
        value:"obv_0",
        description:"OBV能量潮"
      },
      {
        name:"OBV（变体）",
        value:"obv_1",
        description:"变体OBV能量潮"
      },
      {
        name:"VMA",
        value:"vma",
        description:"VMA量均线"
      },
      {
        name:"PVT（原指标）",
        value:"pvt_0",
        description:"PVT量价趋势（原指标）"
      },
      {
        name:"PVT（每天变化值）",
        value:"pvt_1",
        description:"PVT量价趋势（每天变化值）"
      },
      {
        name:"MFI",
        value:"mfi",
        description:"资金流量指标"
      },
    ]

    //动量因子（涨跌）
    const motiveFactorInfo=[
      {
        name:"MACD",
        value:"macd",
        description:"指数平滑异动移动平均线"
      },
      {
        name:"CCI",
        value:"cci",
        description:"顺势指标"
      },
      {
        name:"ROC",
        value:"roc",
        description:"变动率指标"
      },
      {
        name:"TRIX",
        value:"trix",
        description:"三重指数平滑平均线"
      },
      {
        name:"RSI",
        value:"rsi",
        description:"相对强弱指标"
      },
      {
        name:"DPO",
        value:"dpo",
        description:"区间震荡线"
      },
      {
        name:"均线收盘价距离",
        value:"ma_close_dis",
        description:"均线与收盘价距离"
      },
      {
        name:"均线之间距离",
        value:"ma_ma_dis",
        description:"10日均线与5日均线之间距离"
      },
      {
        name:"BIAS",
        value:"bias",
        description:"乖离率"
      },
    ]

    //波动类因子（波动类、振幅）
    const fluctuateFactorInfo=[
      {
        name:"振幅",
        value:"amplitude",
        description:"5日振幅"
      },
      {
        name:"振幅（10日）",
        value:"amplitude_10",
        description:"10日振幅"
      },
      {
        name:"价格轨迹效率",
        value:"price_efficiency",
        description:"5日价格轨迹效率"
      },
      {
        name:"价格轨迹效率（10日）",
        value:"price_efficiency_10",
        description:"10日价格轨迹效率"
      },
      {
        name:"价格重心",
        value:"price_center",
        description:"使用5日移动平均线作为价格重心，重心高低对比间隔为3"
      },
      {
        name:"平均振幅",
        value:"avg_daily_amplitude",
        description:"5日平均振幅"
      },
      {
        name:"ATR",
        value:"atr",
        description:"平均真实波动幅度"
      },
      {
        name:"布林线上",
        value:"boll_upperband",
        description:"布林线上界"
      },
      {
        name:"布林线中",
        value:"boll_middleband",
        description:"布林线中间"
      },
      {
        name:"布林线下",
        value:"boll_lowerband",
        description:"布林线下界"
      },
    ]

    //分析师因子（预测）
    const analystFactorInfo=[]

    //每日指标
    const dailyBasicFactorInfo=[
      {
        name:'换手率（%）',
        value:'turnover_rate',
        description:'换手率（%）'
      },
      {
        name:'换手率（自由流通股）',
        value:'turnover_rate_f',
        description:'换手率（自由流通股）'
      },
      {
        name:'量比',
        value:'volume_ratio',
        description:'量比'
      },
      {
        name:'市盈率',
        value:'pe',
        description:'市盈率（总市值/净利润， 亏损的PE为空）'
      },
      {
        name:'市盈率（TTM）',
        value:'pe_ttm',
        description:'市盈率（TTM，亏损的PE为空）'
      },
      {
        name:'市净率',
        value:'pb',
        description:'市净率（总市值/净资产）'
      },
      {
        name:'市销率',
        value:'ps',
        description:'市销率'
      },
      {
        name:'市销率（TTM）',
        value:'ps_ttm',
        description:'市销率（TTM）'
      },
      {
        name:'股息率（%）',
        value:'dv_ratio',
        description:'股息率（%）'
      },
      {
        name:'股息率（TTM）',
        value:'dv_ttm',
        description:'股息率（TTM）'
      },
    ]

    //日线行情
    const dailyFactorInfo=[
      {
        name:'开盘价',
        value:'open',
        description:'开盘价'
      },
      {
        name:'最高价',
        value:'high',
        description:'最高价'
      },
      {
        name:'最低价',
        value:'low',
        description:'最低价'
      },
      {
        name:'收盘价',
        value:'close',
        description:'收盘价'
      },
      {
        name:'涨跌额',
        value:'change',
        description:'涨跌额'
      },
      {
        name:'涨跌幅',
        value:'pct_chg',
        description:'涨跌幅（未复权）'
      },
      {
        name:'成交量',
        value:'vol',
        description:'成交量（手）'
      },
      {
        name:'成交额',
        value:'amount',
        description:'成交额（千元）'
      },
    ]

    //现金流量表
    const cashflowFactorInfo=[
      {
        name:'经营活动现金流入小计',
        value:'c_inf_fr_operate_a',
        description:'经营活动现金流入小计'
      },
      {
        name:'经营活动现金流出小计',
        value:'st_cash_out_act',
        description:'经营活动现金流出小计'
      },
    ]

    export default {
      name: "FactorInfo",
      dailyFactorInfo,
      dailyBasicFactorInfo,
      cashflowFactorInfo,
      profitFactorInfo,
      valueFactorInfo,
      developFactorInfo,
      emotionFactorInfo,
      motiveFactorInfo,
      fluctuateFactorInfo,
      analystFactorInfo
    }
</script>

<style scoped>

</style>
